config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "home#index"

  get 'home/index'

  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'

  resources :articles do
    resources :comments, only: [:create]
  end
  resource :contacts, only: [:new, :create], path_names: {:new => ''}

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true, length: {maximum: 140}
  validates :text, presence: true, length: {maximum: 4000}
  has_many :comments

  def subject
    title
  end

  def last_comment
    comments.last
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, presence: true, length: {maximum: 4000}
  belongs_to :article
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :email, presence: true
  validates :message, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_filter :authenticate_user!, :only => [:new, :create]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
  end

  def create
    @article = Article.new(article_params)
    @article.username = current_user.username
    if @article.save
      redirect_to @article
    else
      render action: 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
    if !(user_signed_in?) or current_user.username != @article.username
      redirect_to article_path
    end
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render action: 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @art = Article.find(params[:article_id])
    @article = @art.comments.new(comment_params)
    @article.author = current_user.username
    @article.save

    redirect_to article_path(@art)
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.valid?
      @contact.save
    else
      render action: 'new'
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :message)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def terms
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/edit.html.erb
<div class="row">
  <h1>Edit article</h1>
</div>

<div class="row">
  <div class="col-xs-12">
    <%= form_for :article, url: article_path(@article), method: :put do |f| %>
        <p>
          <%= f.label :title %><br/>
          <%= f.text_field :title, class: "form-control", style: "width: 40%;" %>
        </p>
        <p>
          <%= f.label :text %><br/>
          <%= f.text_area :text, class: "form-control", style: "width: 50%; height: 100px" %>
        </p>
        <p>
          <%= f.submit class: "btn btn-primary" %>
        </p>
    <% end %>
  </div>
</div>

app/views/articles/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <% @articles.each do |article| %>
        <h2><%= article.title %></h2>
        <p><%= article.text %></p>
        <div id="small">
          <p>Writer is <%= article.username %> at <%= article.created_at %></p>
          <%= link_to 'Comments', article_path(article) %>
          <% if user_signed_in? && article.username == current_user.username %>
              | <%= link_to 'Edit', edit_article_path(article) %>
              | <%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: 'Are you sure?'} %>
          <% end %>
          </div>
          <hr>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1><%= t('articles.new_article') %></h1>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <%= form_for :article, url: articles_path do |f| %>
        <p>
          <%= f.label :title %><br/>
          <%= f.text_field :title, class: "form-control", style: "width: 40%;" %>
        </p>
        <p>
          <%= f.label :text %><br/>
          <%= f.text_area :text, class: "form-control", style: "width: 50%; height: 100px" %>
        </p>
        <p>
          <%= f.submit class: "btn btn-primary" %>
        </p>
    <% end %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="post">
  <h1><%= @article.title %></h1>
  <p><%= @article.text %></p>
  <p id="small">Writer is <%= @article.username %> at <%= @article.created_at %></p>
</div>

<br>
<h2>Comments:</h2>
<% @article.comments.each do |comment| %>
    <div class="comment">
      <p><%= comment.body %></p>
      <p id="small">Commented <%= comment.author %> at <%= comment.created_at %></p>
    </div>
    <hr/>
<% end %>
<br/>

<% if user_signed_in? %>
    <h2>Write a comment:</h2>
    <%= form_for ([@article, @article.comments.build]) do |f| %>
        <p>
          <%= f.label :body %><br/>
          <%= f.text_area :body, class: "form-control", style: "width: 40%;" %>
        </p>
        <p>
          <%= f.submit class: "btn btn-primary" %>
        </p>
    <% end %>
<% end %>

app/views/contacts/create.html.erb
<h1><%= t('contacts.send_contact') %></h1>

app/views/contacts/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1><%= t('contacts.new_contacts') %></h1>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <%= form_for :contact, url: contacts_path do |f| %>
        <% if @contact && @contact.errors.any? %>
            <ul>
              <% @contact.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
        <% end %>
        <p>
          <%= f.label :email %><br/>
          <%= f.text_field :email, class: "form-control", style: "width: 35%;" %>
        </p>
        <p>
          <%= f.label :message %><br/>
          <%= f.text_area :message, class: "form-control", style: "width: 40%; height: 100px;" %>
        </p>
        <p>
          <%= f.submit 'Send Message', class: "btn btn-primary" %>
        </p>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<h1>This is Home page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <link data-require="bootstrap-css@3.3.6" data-semver="3.3.6" rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.css" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <div class="row">
    <div class="col-xs-12 hidden-xs">
      <nav class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><a href="/">Home</a></li>
          <li><a href="/articles">Articles</a></li>
          <li><a href="/articles/new">New Article</a></li>
          <li><a href="/about">About</a></li>
          <li><a href="/contacts">Contacts</a></li>
          <li><a href="/terms">Terms</a></li>
          <li>
            <% if user_signed_in? %>
                <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
            <% else %>
              <%= link_to 'Sign In', new_user_session_path %>
            <% end %>
          </li>
        </ul>
      </nav>
      <% if user_signed_in? %>
        <p><u><%= current_user.username %></u></p>
      <% end %>
    </div> <!--/.col-->
    <div class="col-xs-12 visible-xs">
      <div class="bs-example">
        <ul class="nav nav-pills">
          <li style="padding-top:8px;">
            <div style="float: right;" class="dropdown">
              <button class="btn btn-lg btn-default dropdown-toggle" type="button" data-toggle="dropdown">Menu</button>
              <ul class="dropdown-menu">
                <li><a href="/articles">Articles</a></li>
                <li><a href="/articles/new">New Articles</a></li>
                <li><a href="/contacts">Contacts</a> </li>
                <li><a href="/terms">Terms</a></li>
                <li><a href="/about">About</a></li>
                <li>
                  <% if user_signed_in? %>
                      <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
                  <% else %>
                      <%= link_to 'Sign In', new_user_session_path %>
                  <% end %>
                </li>
              </ul>
            </div>
          </li>
          <li style="padding-top:7px; font-size: 160%"><a href="/">Home</a></li>
          <% if user_signed_in? %>
              <p><u><%= current_user.username %></u></p>
          <% end %>
        </ul>
      </div>
    </div> <!--/.col-->
  </div>  <!--/.row-->
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  <div class="row">
    <div class="col-md-1 col-lg-1"></div>
    <div class="col-md-10 col-lg-10">
      <%= yield %>
    </div>
    <div class="col-md-1 col-lg-1"></div>
  </div>
</div> <!--/.container-->

</body>
</html>

app/views/pages/about.html.erb
<h2>About Us</h2>
<p>This is my first blog, written on Ruby on Rails</p>
<p>It was written as part of a programming course on Ruby</p>

app/views/pages/terms.html.erb
<h2>Terms of Service</h2>